.Dd $Mdocdate: August 01 2020$
.Dt NETINI-DOT 1
.Os
.
.
.Sh NAME
.
.Nm netini-dot
.Nd turn config.ini files into a dot formatted plot
.
.
.Sh SYNOPSIS
.
.Nm netini-dot
.Op Fl options
.Ar
.
.
.Sh DESCRIPTION
.
The
.Nm
utility
.
.
.
.Sh ENVIRONMENT
.
.
.
.Sh FILES
.
.
.
.Sh EXIT STATUS
.
.Ex -std
.
.
.Sh EXAMPLES
.
.
.
.Sh DIAGNOSTICS
.
.
.
.Sh SEE ALSO
.
.Xr foobar 1
.
.
.Sh STANDARDS
.
.
.
.Sh HISTORY
.
.
.
.Sh AUTHORS
.
.An <author-name>
.Aq Mt <author-email>
.
.
.Sh CAVEATS
.
.
.
.Sh BUGS
.
